openapi: 3.0.0
info:
  title: Delilah Resto
  description: API for the delilah resto application, which handles restaurant orders, can register to place orders and administrators can upload new meals to the application.
  contact:
    email: patyrodriguezs10@gmail.com
  version: 1.0.0
externalDocs:
  description: Github Repository
  url: https://github.com/pattyrodriguez/Delilah-Resto.git
paths:
  /users/signin:
    post:
      tags:
        - clients
        - admins
      summary: authenticate users or administrators
      requestBody:
        content:
           application/json:
              schema:
                properties:
                  user_mail:
                    type: string
                    example: delilah@correo.com
                  user_password:
                    type: string
                    example: 1234578Delilah
        description: user credentials
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  token:
                      type: string
                      example: aleatorio
                  user:
                    $ref: '#/components/schemas/User'
          description: identificated user
        '401':
          description: user does not exist or invalid credentials
  /users:
    get:
      tags: 
        - admins
      summary: get all users
      security: 
        - autenticationJWT: []
      responses:
        '200':
          description: meal list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        '500':
          description: internal error
    post:
      tags:
        - clients
        - admins
      summary: register users or administrators
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        description: User data or admin data
      responses:
        '200':
          description: user successfully created
        '500':
          description: error creating user. internal error
          
  /users/logout:
    post:
      tags: 
        - admins
        - clients
      summary: logout an user
      security: 
        - autenticationJWT: []
      responses:
        '200':
          description: user logout
        '500':
          description: internal error
   
  /users/{idUser}:
    get:
      tags:
        - clients
        - admins
      parameters:
        - name: idUser
          in: path
          required: true
          description: unique user id
          schema:
            type: string
      summary: get a user
      security: 
        - autenticationJWT: []
      responses:
        '200':
          description: user with the specified id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '500':
          description: internal error
        '404':
          description: user not found
    put:
      tags:
        - clients
        - admins
      summary: update a user
      parameters:
        - name: idUser
          in: path
          required: true
          description: unique user id
          schema:
            type: string
      description: update a user to the system
      security:
        - autenticationJWT: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        description: user to update
      responses:
        '200':
          description: user updated
        '401':
          description: Unauthorized user to do this operation or invalid token
        '404':
          description: user not found
    delete:
      tags:
        - admins
      summary: delete a user
      parameters:
        - name: idUser
          in: path
          required: true
          description: unique user id
          schema:
            type: string
      description: delete a user to the system
      security:
        - autenticationJWT: []
      responses:
        '200':
          description: user deleted
        '401':
          description: Unauthorized user to do this operation or invalid token
        '404':
          description: user not found
  /products:
    get:
      tags:
        - clients
        - admins
      summary: get list of all products
      responses:
        '200':
          description: meal list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        '500':
          description: internal error
    post:
      tags:
        - admins
      summary: adds a product
      description: Adds a product to the system
      security: 
        - autenticationJWT: []
      responses:
        '201':
          description: item created
        '400':
          description: invalid input, object invalid
        '409':
          description: an existing product already exists
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
        description: product to add
  
  /products/{idProduct}:
    get:
      tags:
        - clients
        - admins
      parameters:
        - name: idProduct
          in: path
          required: true
          description: unique product id
          schema:
            type: string
      summary: get a product
      responses:
        '200':
          description: product with the specified id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '500':
          description: internal error
        '404':
          description: product not found
    put:
      tags:
        - admins
      summary: update a product
      parameters:
        - name: idProduct
          in: path
          required: true
          description: unique product id
          schema:
            type: string
      description: update a product to the system
      security:
        - autenticationJWT: []
      responses:
        '200':
          description: product updated
        '401':
          description: Unauthorized user to do this operation or invalid token
        '404':
          description: product not found
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
        description: product to update
    delete:
      tags:
        - admins
      summary: delete a product
      parameters:
        - name: idProduct
          in: path
          required: true
          description: unique product id
          schema:
            type: string
      description: delete a product to the system
      security:
        - autenticationJWT: []
      responses:
        '200':
          description: product deleted
        '401':
          description: Unauthorized user to do this operation or invalid token
        '404':
          description: product not found
      
  /orders:
    get:
      tags:
        - clients
        - admins
      summary: get list of all orders
      security:
        - autenticationJWT: []
      responses:
        '200':
          description: order list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
        '500':
          description: internal error
    post:
      tags:
        - clients
      summary: adds a order
      description: Adds a order to the system
      security: 
        - autenticationJWT: []
      responses:
        '201':
          description: order created
        '400':
          description: invalid input, object invalid
        '401':
          description: Unauthorized user to do this operation or invalid token
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
        description: order to add
   
  /orders/{idOrder}:
    get:
      tags:
        - clients
        - admins
      summary: get a order
      security:
        - autenticationJWT: []
      parameters:
        - name: idOrder
          in: path
          required: true
          description: unique order id
          schema:
            type: string
      responses:
        '200':
          description: order with the specific id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '500':
          description: internal error
        '401':
          description: Unauthorized user to do this operation or invalid token
        '404':
          description: order not found
    post:
      tags:
        - clients
      summary: adds a order
      description: Adds a order to the system
      parameters:
        - name: idOrder
          in: path
          required: true
          description: unique order id
          schema:
            type: string
      security: 
        - autenticationJWT: []
      responses:
        '201':
          description: order created
        '400':
          description: invalid input, object invalid
        '401':
          description: Unauthorized user to do this operation or invalid token
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
        description: order to add
    put:
      tags:
        - admins
      summary: update specific order state
      parameters:
        - name: idOrder
          in: path
          required: true
          description: unique order id
          schema:
            type: string
      description: update specific order state
      security:
        - autenticationJWT: []
      responses:
        '200':
          description: order updated
        '401':
          description: Unauthorized user to do this operation or invalid token
        '404':
          description: order not found
      requestBody:
        content:
          application/json:
            schema:
              properties:
                order_state:
                  type: string
                  example: 'cooking'
        description: order state to update
    delete:
      tags:
        - admins
      summary: delete specific order 
      parameters:
        - name: idOrder
          in: path
          required: true
          description: unique order id
          schema:
            type: string
      description: delete specific order
      security:
        - autenticationJWT: []
      responses:
        '200':
          description: order deleted
        '401':
          description: Unauthorized user to do this operation or invalid token
        '404':
          description: order not found

components:
  schemas:
    Product:
      type: object
      required:
        - product_id
        - product_name
        - product_price
        - product_description
      properties:
        product_id:
          type: integer
          format: int64
          example: 1
        product_name:
          type: string
          example: Burguer
        product_price:
          type: number
          format: double
          example: 30000,00
        product_description:
          type: string
          example: Burger with sesame bread, 3/4 length beef, double cheddar cheese, lettuce, tomato and onion
    User:
      type: object
      required: 
        - user_id
        - user_name
        - user_lastname
        - user_mail
        - user_password
        - user_address
      properties:
        user_id:
          type: integer
          format: int64
        user_name:
          type: string
          example: Delilah
        user_lastname:
          type: string
          example: Resto
        user_mail:
          type: string
          format: mail
          example: delilah@correo.com
        user_phone:
          type: integer
          example: 3008630764
        user_password:
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
        user_address:
          type: string
          example: carrera 63 # 33 60
        user_active:
          type: boolean
          example: false
        
    Order:
      type: object
      required: 
        - order_id
        - order_order_time
        - order_state
        - order_description
        - order_form_payment
        - order_total_price
        - order_user_id
      properties:
        order_id: 
          type: integer
          format: int64
          example: 3
        order_order_time:
          type: string
          format: data-time
        order_state:
          type: string
          example: Enviando
        order_description:
          type: string
        order_form_payment:
          type: string
          example: efectivo
        order_total_price:
          type: number
          format: double
        order_user_id: 
          type: integer
          format: int64
        order_products:
          type: array
          items:
            $ref: '#/components/schemas/ProductOrder'
    ProductOrder:
      type: object
      required: 
        - order_id
        - product_id
        - quantity
      properties:
        order_id: 
          type: integer
          format: int64
          example: 3
        product_order:
          $ref: '#/components/schemas/Product'
        quantity:
          type: integer
          format: int64
  securitySchemes:
    autenticationJWT:
      type: http
      scheme: bearer
      bearerFormat: JWT
      
      